version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 900300Rf!
      POSTGRES_DB: hw1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hw1_app
    environment:
      DB_USER: postgres
      DB_PASSWORD: 900300Rf!
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: hw1
    depends_on:
      - db

volumes:
  postgres_data: