"""tables initialized

Revision ID: 9a01c3978523
Revises: 
Create Date: 2026-04-14 15:24:58.803897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a01c3978523'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_index(op.f('ix_customers_CustomerID'), 'customers', ['CustomerID'], unique=False)
    op.create_table('products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ProductID'),
    sa.UniqueConstraint('ProductName')
    )
    op.create_index(op.f('ix_products_ProductID'), 'products', ['ProductID'], unique=False)
    op.create_table('orders',
    sa.Column('OrderID', sa.Integer(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.DateTime(), nullable=False),
    sa.Column('TotalAmount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_index(op.f('ix_orders_OrderID'), 'orders', ['OrderID'], unique=False)
    op.create_table('order_items',
    sa.Column('OrderItemID', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('ProductID', sa.Integer(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.ForeignKeyConstraint(['ProductID'], ['products.ProductID'], ),
    sa.PrimaryKeyConstraint('OrderItemID')
    )
    op.create_index(op.f('ix_order_items_OrderItemID'), 'order_items', ['OrderItemID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_OrderItemID'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_OrderID'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_ProductID'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_CustomerID'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
