"""fixed to_user field in interactions

Revision ID: a734353f36ce
Revises: 5c774c984cb8
Create Date: 2026-04-02 12:13:38.859216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a734353f36ce'
down_revision: Union[str, Sequence[str], None] = '5c774c984cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interactions_to_user_fkey'), 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'users', ['to_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_to_user_fkey'), 'interactions', 'profiles', ['to_user'], ['id'])
    # ### end Alembic commands ###
